### ISSUE TITLE
Clean peerDependencies

### ISSUE THREAD

**Issue by kuoruan** [CaptainLiao/vite-plugin-webpackchunkname#13]
https://github.com/CaptainLiao/vite-plugin-webpackchunkname/blob/a93c1d79c5b607da81387a4604e5aa2eb6eefbfc/package.json#L49-L50

The `@rollup/plugin-alias` is already in `dependencies` field, it is no need.

And we can mark `rollup` in `peerDependencies` as `optional` with `peerDependenciesMeta`

https://docs.npmjs.com/cli/v7/configuring-npm/package-json#peerdependenciesmeta

This can resolve the warnings in the log:

```
warning " > vite-plugin-webpackchunkname@0.2.0" has unmet peer dependency "@rollup/plugin-alias@*".
warning " > vite-plugin-webpackchunkname@0.2.0" has unmet peer dependency "rollup@^2.67.2".
warning "vite-plugin-webpackchunkname > @rollup/plugin-alias@3.1.9" has unmet peer dependency "rollup@^1.20.0||^2.0.0".
```

**Comment by CaptainLiao** [comment]
what's the `rollup` verison you use? please try update `rollup` and `vite-plugin-webpackchunkname` to latest verion.

**Comment by kuoruan** [comment]
I mean the `peerDependenices` in `package.json` can be cleaned.

the `rollup` is optional for us to use this package. so it can be marked as `optional` in `peerDependencies`

**Comment by CaptainLiao** [comment]
for reduce bundle size, this plugin has not contain `@rollup/plugin-alias` in final assests. 

please update `rollup` and `vite-plugin-webpackchunkname` to latest version.
