### ISSUE TITLE
 a plugin (manualNameChunksPlugin) was used to transform files, but didn't generate a sourcemap for the transformation.

### ISSUE THREAD

**Issue by zhoufenfens** [CaptainLiao/vite-plugin-webpackchunkname#17]
Hi, thanks for your plugin, this is a error when run the vite build:
"Sourcemap is likely to be incorrect: a plugin (manualNameChunksPlugin) was used to transform files, but didn't generate a sourcemap for the transformation. Consult the plugin documentation for help",

vite 4.0.4

**Comment by CaptainLiao** [comment]
Please update `vite-plugin-webpackchunkname@0.2.3`.

**Comment by zhoufenfens** [comment]
thank you, it works.

**Comment by zhoufenfens** [comment]
hi, I found another problem, I use the vant 4 in my project, and use the 'unplugin-vue-components' to auto import the vant ui components,  there is a warning message in Console when use the manualNameChunksPlugin, the vant component could not be recognized by the vue. 
<img width="890" alt="image" src="https://user-images.githubusercontent.com/3303836/210777982-38ae967d-c396-4430-9536-1b17746de2ba.png">
remove the manualNameChunksPlugin plugin  and it was back to normal.

**Comment by CaptainLiao** [comment]
Could please give me a mini reproduction and maybe open a new issue.
