### ISSUE TITLE
"[Vue warn]: Failed to resolve component: van-button"

### ISSUE THREAD

**Issue by zhoufenfens** [CaptainLiao/vite-plugin-webpackchunkname#18]
hi, i found a problem in the Console when deploy the build assets to the web server, the van component could not reconized by the vue.

https://stackblitz.com/edit/vitejs-vite-wbqtdm?file=README.md

the development env  was okay, but it is not okay when run "npm run build" and deploy the dist directory to the web server.

sorry i could not found any online web server could serve the dist dir.

**Comment by zhoufenfens** [comment]
hi,  here is my sample
https://stackblitz.com/edit/vitejs-vite-wbqtdm?file=vite.config.js

run the script "npm run build";
then run the "npm run preview";
the button in news.vue  looks like a text;
<img width="335" alt="image" src="https://user-images.githubusercontent.com/3303836/211140755-10b9140a-a38a-49ec-ad21-8d3f95047516.png">

 then comment the manualChunksPlugin(),
<img width="258" alt="image" src="https://user-images.githubusercontent.com/3303836/211140803-7b1e3403-a53e-4f03-8ec2-9aa0bdfae64e.png">

rerun "npm run build & npm run preview"
the button in news.vue works well
<img width="324" alt="image" src="https://user-images.githubusercontent.com/3303836/211140789-c0b4e622-57e6-44a0-8f49-0b70eea49db5.png">

**Comment by zhoufenfens** [comment]
then,  I created a news2 component, add removed the comment "/* webpackChunkname: news2 */"
<img width="658" alt="image" src="https://user-images.githubusercontent.com/3303836/211140982-bfaaf480-8fe4-4127-b215-42e33f802710.png">
this worked well for the News2 even though add the manualChunksPlugin()
<img width="354" alt="image" src="https://user-images.githubusercontent.com/3303836/211141084-bddd6827-5ed5-45df-b006-11bf9c808de8.png">

**Comment by CaptainLiao** [comment]
@zhoufenfens 

Please add `include: [/\.vue$/, /\.vue\?/]` in vite.config.js:
````js
import Components from 'unplugin-vue-components/vite';
...
  plugins: [
    Components({
      resolvers: [VantResolver()],
      include: [/\.vue$/, /\.vue\?/]
    }),
  ],
...
````

**Comment by zhoufenfens** [comment]
thanks, it worked.
