### ISSUE TITLE
How to support when applying `serve` rather than `build`?

### ISSUE THREAD

**Issue by aleen42** [CaptainLiao/vite-plugin-webpackchunkname#19]

**Comment by CaptainLiao** [comment]
`serve`phase do not need this, do u hava a use case?

**Comment by aleen42** [comment]
In my case, I hope to split code during creating a dev server

**Comment by CaptainLiao** [comment]
I'm afraid that it's not support.

**Comment by aleen42** [comment]
Due to? I still need to know the mechanism of code splitting in Vite, or Rollup.

**Comment by CaptainLiao** [comment]
Vite can't compile user's code when excute `vite` as well as `npm run dev`. no compile no code splitting.

 [in vite guide](https://vitejs.dev/guide/why.html):
>Vite serves source code over [native ESM](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules). This is essentially letting the browser take over part of the job of a bundler: Vite only needs to transform and serve source code on demand, as the browser requests it.

**Comment by aleen42** [comment]
That's why I want another PR for Vite to support using rollup to build the dev server

**Comment by luckydonald** [comment]
then you should simply use Webpack. No use in using Vite without using Vite.
