### ISSUE TITLE
Cannot find module 'es-module-lexer'

### ISSUE THREAD

**Issue by daniel-lij** [CaptainLiao/vite-plugin-webpackchunkname#2]
10:00:39 ├F10: AM┤ [vite] Cannot find module 'es-module-lexer'
Require stack:
- D:\yoteam\wannan project\p5\node_modules\vite-plugin-webpackchunkname\dist\vite-plugin-webpackchunkname.js
- D:\yoteam\wannan project\p5\vite.config.js
- D:\yoteam\wannan project\p5\node_modules\vite\dist\node\chunks\dep-9c153816.js
- D:\yoteam\wannan project\p5\node_modules\vite\dist\node\cli.js
- D:\yoteam\wannan project\p5\node_modules\vite\bin\vite.js

**Comment by CaptainLiao** [comment]
Please run `yarn add -D vite-plugin-webpackchunkname@0.0.7`.

cause vite v2.9.0 removed es-module-lexer.
