### ISSUE TITLE
Does not work with node_modules ? 

### ISSUE THREAD

**Issue by eMerzh** [CaptainLiao/vite-plugin-webpackchunkname#21]
thanks for your work, i'm trying to migrate from webpack and that could be handy.

i'm trying to do something like this :
```
function Excalidraw({ initialData, onChange, readOnly = false, className }, ref) {
	const [Comp, setComp] = useState(null)

	useEffect(() => {
		import(/* webpackChunkName: "excalidraw" */ '@excalidraw/excalidraw').then(mod => setComp(mod.default))
	})

//...
```

but i got
>[vite]: Rollup failed to resolve import "@excalidraw/excalidraw?chunkName=excalidraw" from "/Users/b.maron/code/elium-web/src/components/common/Excalidraw/Excalidraw.jsx".

i tried to export it via manualChunks but it doesn't seems to work 🤔  

am i doing it wrong?

**Comment by CaptainLiao** [comment]
sorry, it's not support node_modules for now.

see https://github.com/vitejs/vite/pull/8824

**Comment by eMerzh** [comment]
arg yes... i saw that, but thought there was a work around.... 

I've removed the comment, and used manualChunks ....
it build 🎉 
but does not load 😅  ... i'll try to understand why

**Comment by eMerzh** [comment]
@CaptainLiao not sure if bug or misuse.. 

but the error i get is : 
```
options.js:10 Uncaught ReferenceError: Cannot access 'F' before initialization
    at options.js:10:14
    at options.js:92:22
```

with a chunk composed of something like this (source mapped): 
```
var _slate = require("slate");

var _immutable = require("immutable");
```

any idea where that could come from ? 
thanks

**Comment by CaptainLiao** [comment]
no idea.😂

Could u please give a mini repro which help me to figure out.
