### ISSUE TITLE
Does not work with defineAsyncComponent

### ISSUE THREAD

**Issue by yuanjinyong** [CaptainLiao/vite-plugin-webpackchunkname#23]
It work in router 
export default [
  {path: 'app', component: () => import(/* webpackChunkName: "platform-tool-app" */ './app/List.vue')}
]

But does not work with defineAsyncComponent
  components: {
    Detail: defineAsyncComponent(() => import(/* webpackChunkName: "platform-tool-app" */ './Detail.vue'))
  }

It still generate Detail.1939b6b9.js

**Comment by CaptainLiao** [comment]
To speed up production build, this plugin only compiles `.js or .ts` files. 

Since code splitting is already in use with routes， I dont think `defineAsyncComponent` is necessary.

Do you have any specific requirements?

**Comment by benlavalley** [comment]
> To speed up production build, this plugin only compiles `.js or .ts` files.
> 
> Since code splitting is already in use with routes， I dont think `defineAsyncComponent` is necessary.
> 
> Do you have any specific requirements?

If you're just loading the components within a page, and not manually specifying your own routes yet?

**Comment by jonnedeprez** [comment]
I think this is a relevant question and my use case applies to it. I have a page that renders a pdf in the body. Most browsers have a built-in native pdf viewer, so my app can usually rely on that one. For those few browsers that don't have it, I could use `vue-pdf-embed` and choose at runtime to pull in a different component that uses this library, but the library's gzipped size is already 700k. I would only want to load this giant library if rendering pdf is not supported natively. I tried this: 
```
const AsyncVuePdfEmbedWrapper = defineAsyncComponent(
  () => import(/* webpackChunkName: "pdf" */ './VuePdfEmbedWrapper.vue')
);

const renderComponent = computed(() =>
  navigator.pdfViewerEnabled
      ? NativePdfRenderer
      : AsyncVuePdfEmbedWrapper
);

 <component :is="renderComponent"  :url="url" />
```
But it only puts my tiny wrapping component in a separate chunk. The library `vue-pdf-embed` is still in the vendors chunk.

**Comment by CaptainLiao** [comment]
Sorry reply this lately. Just remove magic comments below，vite will handle it properly:
````
const AsyncVuePdfEmbedWrapper = defineAsyncComponent(
  () => import('./VuePdfEmbedWrapper.vue')
);
````
Let me know if I am wrong.Provide a sample is more helpful. thks.
@jonnedeprez
