### ISSUE TITLE
Does not work with  /* webpackChunkName: "[request]" */

### ISSUE THREAD

**Issue by chaomashi** [CaptainLiao/vite-plugin-webpackchunkname#24]
Does not work with  /* webpackChunkName: "[request]" */

**Comment by CaptainLiao** [comment]
name limited by `/\?chunkName=([\w-.]*)/`

see: https://github.com/CaptainLiao/vite-plugin-webpackchunkname/blob/master/src/share.ts#L12C28-L12C51
