### ISSUE TITLE
考虑升级支持更新版本的rollup吗

### ISSUE THREAD

**Issue by luoxianchao** [CaptainLiao/vite-plugin-webpackchunkname#25]
与不同插件共同使用时，其他插件依赖或者项目依赖的rollup版本过高，同该插件依赖版本存在冲突，导致不起作用

**Comment by CaptainLiao** [comment]
我目前没这个需求，所以你看看：

1. 可否提供下最小的复现demo。
2. 或者尝试修改本项目 package.json 中 rollup 相关的版本，发个pr给我。

**Comment by CaptainLiao** [comment]
1.0.0 版本已去掉对rollup的强制依赖。
