### ISSUE TITLE
Invalid ESM module published but "type": "module" is in package.json

### ISSUE THREAD

**Issue by zewish** [CaptainLiao/vite-plugin-webpackchunkname#27]
Hey @CaptainLiao!

We've been using your plugin for a project of ours and we've been really quite happy with the code splitting results.
Thank you for taking the time to support this plugin!

Unfortunately the latest update to version 1.0.0 broke imports in our Vite 5.0 config.
The issue comes from the way you are publishing the module - the Rollup build output format is currently set to "cjs" instead of "module". So when the module is imported into `vite.config.ts` it breaks because it's not an actual ESM module.

The fix should be pretty easy - just change the output format to "module" in `rollup.config.js`, then rebuild and republish the module.

Note: I could do a PR, but it's an easy fix, so I decided to file a bug report instead.

**Comment by CaptainLiao** [comment]
Thanks. I release v1.0.1 to resolve this problem.

**Comment by zewish** [comment]
Seems to be fixed, closing the issue.
