### ISSUE TITLE
Wrong packaging order with css

### ISSUE THREAD

**Issue by joy-yu** [CaptainLiao/vite-plugin-webpackchunkname#29]
When I used manualChunksPlugin, I found that there was a problem with the css packaging order.

I have put `import './styles/app-main.scss';` in the first line in `main.ts`.

In the final css packaging product, this part of css should be at the first. But that's not actually the case.

**Comment by joy-yu** [comment]
🤔 It seems like a vite bug, so I closed the issue here. https://github.com/vitejs/vite/issues/6375

**Comment by BranceLee** [comment]
check the `https://github.com/vitejs/vite/issues/6375#issuecomment-2133064752`
