### ISSUE TITLE
Build error caused by path delimiter in magic comments

### ISSUE THREAD

**Issue by magra-cmm** [CaptainLiao/vite-plugin-webpackchunkname#30]
Hey!

We are currently migrating our React project from Webpack to Vite and encountering an issue when using this plugin. 

In Webpack, magic comments in dynamic imports can contain paths. For example, something like 
`import(/* webpackChunkName: "components/counter" */"./components/CounterButton")` 
will create a chunk inside a `components` directory when generating a build. 

However, when using `vite-plugin-webpackchunkname` in a Vite project this syntax causes an error:
```
error during build:
Error: [vite:esbuild] Invalid loader value: "counter"
file: /project/workspace/src/components/CounterButton.tsx?chunkName=components.counter
```

As can be seen, the import with the magic comment gets converted in such a way that the chunk name is attached to the import using the `chunkName` parameter where the path delimiter (`/`) is replaced with a `.` The`.` is what's causing the build error.

I have created a small [Sandbox project](https://codesandbox.io/p/devbox/hungry-worker-xk9xhm?workspaceId=f8d54096-b508-4f23-844f-2bf22482495b&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clxu5qiqb00073b6metfr11pq%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clxu5qiqb00023b6mmvn2fn57%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clxu5qiqb00043b6mxohb6zb0%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clxu5qiqb00063b6memxrulx2%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clxu5qiqb00023b6mmvn2fn57%2522%253A%257B%2522id%2522%253A%2522clxu5qiqb00023b6mmvn2fn57%2522%252C%2522activeTabId%2522%253A%2522clxu6ajl000bq3b6mepo6vhxb%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxu5qiqb00013b6mml3bm279%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fnode_modules%252F.pnpm%252Fesbuild%2522%252C%2522id%2522%253A%2522clxu6ajl000bq3b6mepo6vhxb%2522%252C%2522mode%2522%253A%2522temporary%2522%257D%255D%257D%252C%2522clxu5qiqb00063b6memxrulx2%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxu5qiqb00053b6mayrx7lok%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clxu5qiqb00063b6memxrulx2%2522%252C%2522activeTabId%2522%253A%2522clxu5qiqb00053b6mayrx7lok%2522%257D%252C%2522clxu5qiqb00043b6mxohb6zb0%2522%253A%257B%2522id%2522%253A%2522clxu5qiqb00043b6mxohb6zb0%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxu5qiqb00033b6mrp12a4s2%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clxu5qiqb00033b6mrp12a4s2%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) to easily replicate this behavior. Simply run `pnpm run build` to observe the build failing. 

### Expected behavior

The plugin should handle paths in magic comments, creating chunks in the specified directories without errors.

### Suggested Fix

For the `chunkName`, replace the path delimiter with a different special character other than `.`, e.g. 2 underscores `__`. Note that this character then has to be converted back into the proper path delimiter. This is already implemented, but it's important that the temporary path delimiter replacement is modified in both places (see below).

https://github.com/CaptainLiao/vite-plugin-webpackchunkname/blob/ce2b8f5f305789cbf4f33d2b1a62a91b3acf665f/src/index.ts#L91

https://github.com/CaptainLiao/vite-plugin-webpackchunkname/blob/ce2b8f5f305789cbf4f33d2b1a62a91b3acf665f/src/manualChunksConfig.ts#L105

**Comment by CaptainLiao** [comment]
Great idea. 

v1.0.3 fix this.

@magra-cmm
