### ISSUE TITLE
Overrides anything set in build.rollupOptions.output.manualChunks

### ISSUE THREAD

**Issue by fc** [CaptainLiao/vite-plugin-webpackchunkname#8]
Vite docs for reference:
https://vitejs.dev/guide/build.html#customizing-the-build

In our config we want to be able to specify some specific dependencies as manual chunks but when using this vite plugin it will override what we set here:

```
        build: {
            outDir: "build",
            rollupOptions: {
                output: {
                    // Rollup docs - https://rollupjs.org/guide/en/#outputmanualchunks
                    manualChunks: {
                        lodash: ["lodash"]
                    }
                }
            }
        },
```

It looks like this plugin needs an update here to spread on any existing ones:
https://github.com/CaptainLiao/vite-plugin-webpackchunkname/blob/master/src/index.ts#L109-L118

**Comment by CaptainLiao** [comment]
It's a little bit complicated. For now, I dont hava a good idea to handle this.

PR welcom.

**Comment by fc** [comment]
You're right this is a bit complicated.  I made 2 attempts. The first attempt won't work and is indeed very complicated.  The second attempt at least provides a way to work with it.

This is the first direction I went but I have no idea how to resolve the id:
```
+        const userDefinedChunks = output.manualChunks
+          ? { ...output.manualChunks }
+          : undefined
         Object.assign(userConfig.build.rollupOptions.output, {
-          manualChunks: manualChunksConfig,
+          manualChunks: (
+            id: string,
+            opts: { getModuleInfo: GetModuleInfo; getModuleIds: any }
+          ) => {
+            if (userDefinedChunks) {
+              for (const [key, modules] of Object.entries(userDefinedChunks)) {
+                // ... not sure what to do here...
+                // how could we resolve it here?
+                if (modules.includes(id)) {
+                  return key
+                }
+              }
+            }
+            return manualChunksConfig(id, opts)
+          },
         })
       }
```


But here is something that could work that is less complicated and at least provides an escape hatch:

```
diff --git a/src/index.ts b/src/index.ts
index ae08c22..897de40 100644
--- a/src/index.ts
+++ b/src/index.ts
@@ -128,10 +128,27 @@ export const manualChunksPlugin = function (): Plugin {
           return item
         })
       } else {
+        const userDefinedChunks =
+          typeof output.manualChunks === 'function'
+            ? output.manualChunks
+            : undefined
+
         Object.assign(userConfig.build.rollupOptions.output, {
-          manualChunks: manualChunksConfig,
+          manualChunks: (
+            id: string,
+            opts: { getModuleInfo: GetModuleInfo; getModuleIds: any }
+          ) => {
+            if (userDefinedChunks) {
+              const result = userDefinedChunks(id, opts)
+              if (result) {
+                return result
+              }
+            }
+            return manualChunksConfig(id, opts)
+          },
         })
       }
```

Then in `vite.config.ts` I do something like this:

```
        manualChunks: (
          id: string
        ) => {
          if (id.indexOf("node_modules/lodash/") !== -1) {
            return "lodash";
          }
        },
```

@CaptainLiao Would you accept a PR using the second approach?

**Comment by fc** [comment]
Unless I'm overlooking something, it seems odd that using a function doesn't also allow for accessing the default behavior of manualChunks.  IMO they should include a `getNameOfModule` in their `manualChunksApi` to allow access to the default behavior.
https://github.com/rollup/rollup/blob/437131a8c382e9a7fe5efca3ac9bac2685cab325/src/Bundle.ts#L166

rollup needs to be updated to allow access to this behavior.

**Comment by CaptainLiao** [comment]
Make sense, second method is better, it's worth to be merged.

BTW, have a test in your repo?

**Comment by fc** [comment]
Would you be able to publish a new release on npm?

**Comment by CaptainLiao** [comment]
0.2.0 is released.
