### ISSUE TITLE
Rollup failed to resolve import - doesn't take aliases into account

### ISSUE THREAD

**Issue by fc** [CaptainLiao/vite-plugin-webpackchunkname#9]
I have this alias in my config:
```

                {
                    find: /@namespace/some-tools/,
                    replacement: join(__dirname, "pkgs/$1/src/index.ts")
                },
```

Which results in this error at build time:
```
[vite]: Rollup failed to resolve import "@namespace/some-tools?chunkName=some-tools" from "src/components/SomeTools/index.tsx".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
```

In my code I am doing:
```
const SomeTools = React.lazy(() => import(/* webpackChunkName: "some-tools" */ "@namespace/some-tools"));
```

Adding to `build.rollupOptions.external` does seem to resolve it... 

It seems it can also be resolved by adding this extra alias:

```

                {
                    find: /@namespace/some-tools\?chunkName=some-tools/,
                    replacement: join(__dirname, "pkgs/$1/src/index.ts")
                },
```

**Comment by CaptainLiao** [comment]
I dont know what config you use. Could you please give me a sample to reproduce the issue?

**Comment by fc** [comment]
Clone this repos
https://github.com/fc/vite-plugin-webpack-chunkname

then `yarn && yarn build`

**Comment by CaptainLiao** [comment]
upgrade` vite-plugin-webpackchunkname@0.1.1` to fix it.

Commit [here](https://github.com/CaptainLiao/vite-plugin-webpackchunkname/commit/5abba736b25204845c3551e15e4e0e3a82f8d44d)

**Comment by fc** [comment]
this works now, thanks!
